# DataSource Config
    spring:
        datasource:
          driver-class-name: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://193.112.121.129:3306/test?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
          username: root
          password: zsroot
        servlet:
          multipart:
            file-size-threshold: 2048KB